import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Accessibility,
  Activity,
  AlarmClockCheck,
  AppWindow,
  ArrowLeftRight,
  BarChart3,
  BellRing,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Cable,
  CircleDollarSign,
  CircleGauge,
  ClipboardList,
  Cloud,
  CloudCog,
  Code2,
  Combine,
  ConciergeBell,
  ContactRound,
  Database,
  DatabaseBackup,
  DatabaseZap,
  DoorOpen,
  Factory,
  FileChartColumn,
  FileCheck,
  FileCode2,
  FileSearch,
  Fingerprint,
  FolderSync,
  Frame,
  GitBranch,
  Globe,
  GraduationCap,
  HardDriveDownload,
  HardHat,
  Headset,
  HeartPulse,
  History,
  KanbanSquare,
  Landmark,
  Layers,
  LayoutDashboard,
  Link2,
  Lock,
  MailCheck,
  Map,
  MessageCircle,
  MessagesSquare,
  MonitorCheck,
  Network,
  PackageSearch,
  Palette,
  PenLine,
  PenTool,
  PhoneCall,
  Plug,
  Receipt,
  Scale,
  ScanText,
  Search,
  SearchCheck,
  ShieldCheck,
  ShieldPlus,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  TabletSmartphone,
  TestTubes,
  Timer,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  WifiOff,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Explicit icon registry.
 *
 * Content files reference icons by name (a plain string), and this map
 * resolves them. Explicit imports keep tree-shaking intact - we ship only
 * the icons the site actually uses.
 */
const registry: Record<string, LucideIcon> = {
  Accessibility,
  Activity,
  AlarmClockCheck,
  AppWindow,
  ArrowLeftRight,
  BarChart3,
  BellRing,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Cable,
  CircleDollarSign,
  ClipboardList,
  Cloud,
  CloudCog,
  Code2,
  Combine,
  ConciergeBell,
  ContactRound,
  Database,
  DatabaseBackup,
  DatabaseZap,
  DoorOpen,
  Factory,
  FileCheck,
  FileCode2,
  FileSearch,
  Fingerprint,
  FolderSync,
  Frame,
  GitBranch,
  Globe,
  GraduationCap,
  HardDriveDownload,
  HardHat,
  Headset,
  HeartPulse,
  History,
  KanbanSquare,
  Landmark,
  Layers,
  LayoutDashboard,
  Link2,
  Lock,
  MailCheck,
  Map,
  MessageCircle,
  MessagesSquare,
  MonitorCheck,
  Network,
  PackageSearch,
  Palette,
  PenLine,
  PenTool,
  PhoneCall,
  Plug,
  Receipt,
  Scale,
  ScanText,
  Search,
  SearchCheck,
  ShieldCheck,
  ShieldPlus,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  TabletSmartphone,
  TestTubes,
  Timer,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  WifiOff,
  Workflow,
  Wrench,
  Zap,
  // Renamed upstream - registered under the names content files use.
  GaugeCircle: CircleGauge,
  FileBarChart: FileChartColumn,
};

interface IconProps extends LucideProps {
  /** Icon name as referenced in content files. */
  name: string;
}

/** Render a Lucide icon by name; falls back to a neutral box icon. */
export function Icon({ name, ...props }: IconProps) {
  const Component = registry[name] ?? Boxes;
  return <Component aria-hidden="true" {...props} />;
}
