import React from 'react';
import { 
  Building2, 
  Stethoscope, 
  Truck,
  ShieldCheck
} from 'lucide-react';
import SEO from '../components/SEO';

interface CaseStudy {
  client: string;
  industry: string;
  icon: React.ComponentType<any>;
  summary: string;
  problem: string;
  solution: string;
  metrics: { value: string; label: string }[];
  chartData: { label: string; before: number; after: number; unit: string }[];
}

export const CaseStudies: React.FC = () => {
  const caseStudies: CaseStudy[] = [
    {
      client: "Vanguard Textiles Ltd",
      industry: "Manufacturing & Textiles",
      icon: Building2,
      summary: "Consolidating 4 separate spinning mills, raw yarn inventories, and payroll ledgers into a single unified cloud ERP dashboard.",
      problem: "Yarn stocks audits took 48 hours, BOM margins were calculated on manual spreadsheets, and payroll for 600 shift-workers was delayed by a week, causing 12% revenue leakages.",
      solution: "We engineered a modular Manufacturing ERP with automated SKU ledger reconciliations, double-entry financial accounting ledgers, and automated shift-payroll calculation engines.",
      metrics: [
        { value: "-60%", label: "Stock Audits Time" },
        { value: "+38%", label: "Fulfillment Speed" },
        { value: "0%", label: "Ledger Discrepancies" }
      ],
      chartData: [
        { label: "Audit Hours", before: 48, after: 2, unit: "Hrs" },
        { label: "Revenue Leakage", before: 12, after: 0.1, unit: "%" }
      ]
    },
    {
      client: "Aegis Clinic Network",
      industry: "Healthcare & Clinic POS",
      icon: Stethoscope,
      summary: "Automating medical patient queue registration and appointment scheduling using AI Sales Agents and Official WhatsApp CRM.",
      problem: "Clinic reception desks were flooded with phone booking queries, causing 30% patient call abandonment rates, long waiting room queues, and double-bookings.",
      solution: "Configured Official WhatsApp API integrations with a conversational AI appointment scheduler and a custom Clinic Intake Desk Dashboard.",
      metrics: [
        { value: "65%", label: "Bookings Handled by AI" },
        { value: "-75%", label: "Intake Wait Times" },
        { value: "98%", label: "Patient Satisfaction" }
      ],
      chartData: [
        { label: "Wait Time (Min)", before: 35, after: 8, unit: "Min" },
        { label: "Booking Miss Ratio", before: 30, after: 1.2, unit: "%" }
      ]
    },
    {
      client: "Pacific Cargo Systems",
      industry: "Wholesale & Logistics",
      icon: Truck,
      summary: "Streamlining fleet cargo manifests dispatching and real-time proof of delivery uploads via custom mobile driver portals.",
      problem: "Lost paper manifests, delayed driver route allocations from dispatchers, and delayed client invoicing, causing 45-day cash cycle delays.",
      solution: "Developed custom Warehouse Management Systems (WMS) with GPS-synchronized mobile portals, automated route scheduling, and Stripe billing integrations.",
      metrics: [
        { value: "3.2 Days", label: "Average Cash Cycle" },
        { value: "+30%", label: "Fleet Optimization" },
        { value: "0", label: "Lost Delivery Manifests" }
      ],
      chartData: [
        { label: "Cash Cycle (Days)", before: 45, after: 3, unit: "Days" },
        { label: "Admin manifest time", before: 18, after: 1.5, unit: "Hrs" }
      ]
    }
  ];

  return (
    <div className="w-full relative overflow-hidden font-sans">
      <SEO 
        title="Success Case Studies" 
        description="Browse our case studies detailing how ELVTERA designed custom ERPs, AI voice agents, and WhatsApp funnels to optimize operational yields." 
      />

      {/* Hero Header */}
      <section className="relative pt-12 pb-16 bg-slate-50 dark:bg-slate-950/20">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[85%] h-[200px] bg-gradient-glow rounded-full blur-[100px] pointer-events-none"></div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-6">
          <span className="text-brand-blue text-xs font-bold uppercase tracking-wider bg-brand-blue/10 dark:bg-brand-blue/20 px-3.5 py-1.5 rounded-full w-fit mx-auto">
            Client Success
          </span>
          <h1 className="font-display font-extrabold text-4xl sm:text-5xl text-slate-900 dark:text-white tracking-tight">
            Digital Transformation Realized
          </h1>
          <p className="text-xs sm:text-sm text-slate-550 dark:text-slate-400 max-w-lg mx-auto leading-relaxed">
            Read the detailed engineering audits, problem breakdowns, and operational metrics showing the business yields generated by our enterprise solutions.
          </p>
        </div>
      </section>

      {/* Case Studies details list */}
      <section className="py-20 bg-white dark:bg-slate-900 border-y border-slate-200/50 dark:border-slate-800/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-24">
          
          {caseStudies.map((study, idx) => {
            const Icon = study.icon;
            return (
              <div 
                key={idx} 
                className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-stretch pb-16 border-b border-slate-100 dark:border-slate-850 last:border-0 last:pb-0"
              >
                {/* Left side details (7 cols) */}
                <div className="lg:col-span-7 space-y-6 text-left flex flex-col justify-between">
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2.5">
                      <div className="p-2 rounded-xl bg-brand-blue/10 dark:bg-brand-blue/20 text-brand-blue">
                        <Icon className="h-5.5 w-5.5" />
                      </div>
                      <div>
                        <h2 className="font-display font-bold text-xl sm:text-2xl text-slate-900 dark:text-white">
                          {study.client}
                        </h2>
                        <span className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">
                          {study.industry}
                        </span>
                      </div>
                    </div>

                    <p className="text-sm text-slate-650 dark:text-slate-300 font-semibold leading-relaxed">
                      "{study.summary}"
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5 pt-2">
                      <div className="space-y-1.5">
                        <span className="text-xs font-extrabold text-red-500 uppercase tracking-wider block">Operational Bottlenecks</span>
                        <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">{study.problem}</p>
                      </div>
                      <div className="space-y-1.5">
                        <span className="text-xs font-extrabold text-brand-success uppercase tracking-wider block">Implementation Scopes</span>
                        <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">{study.solution}</p>
                      </div>
                    </div>
                  </div>

                  {/* Impact metrics badges */}
                  <div className="grid grid-cols-3 gap-4 pt-6 border-t border-slate-100 dark:border-slate-850">
                    {study.metrics.map((m, mIdx) => (
                      <div key={mIdx} className="space-y-1">
                        <span className="font-display font-extrabold text-2xl sm:text-3xl text-brand-blue dark:text-blue-400 block tracking-tight">
                          {m.value}
                        </span>
                        <span className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider block leading-tight">
                          {m.label}
                        </span>
                      </div>
                    ))}
                  </div>

                </div>

                {/* Right side before-after charts (5 cols) */}
                <div className="lg:col-span-5 bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 rounded-3xl p-6 sm:p-8 flex flex-col justify-between space-y-6 text-left">
                  <div className="space-y-1.5">
                    <span className="text-xs font-extrabold text-slate-440 dark:text-slate-500 uppercase tracking-wider block">
                      Operations Yield Audit
                    </span>
                    <h4 className="font-display font-semibold text-sm text-slate-900 dark:text-white">
                      Metrics Comparison (Before vs After)
                    </h4>
                  </div>

                  {/* Custom CSS Bar Charts */}
                  <div className="space-y-6 grow flex flex-col justify-center">
                    {study.chartData.map((item, cIdx) => {
                      const total = item.before + item.after;
                      const beforePercent = (item.before / total) * 100;
                      const afterPercent = (item.after / total) * 100;
                      
                      return (
                        <div key={cIdx} className="space-y-2">
                          <div className="flex justify-between text-xs font-semibold text-slate-700 dark:text-slate-350">
                            <span>{item.label}</span>
                            <span>{item.before}{item.unit} → <span className="text-brand-success font-bold">{item.after}{item.unit}</span></span>
                          </div>
                          <div className="space-y-1">
                            {/* Before Bar */}
                            <div className="flex items-center space-x-2">
                              <span className="text-xs font-bold text-red-500 w-9 uppercase shrink-0">Before</span>
                              <div className="grow bg-slate-200 dark:bg-slate-800 rounded-full h-3 overflow-hidden">
                                <div 
                                  className="bg-red-400 h-full rounded-full" 
                                  style={{ width: `${Math.max(beforePercent, 8)}%` }}
                                ></div>
                              </div>
                            </div>
                            {/* After Bar */}
                            <div className="flex items-center space-x-2">
                              <span className="text-xs font-bold text-brand-success w-9 uppercase shrink-0">After</span>
                              <div className="grow bg-slate-200 dark:bg-slate-800 rounded-full h-3 overflow-hidden">
                                <div 
                                  className="bg-brand-success h-full rounded-full" 
                                  style={{ width: `${Math.max(afterPercent, 3)}%` }}
                                ></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  <div className="pt-4 border-t border-slate-150 dark:border-slate-850 flex items-center space-x-2 text-xs text-slate-450 italic">
                    <ShieldCheck className="h-4.5 w-4.5 text-brand-teal" />
                    <span>Metrics certified by client stakeholder logs.</span>
                  </div>
                </div>

              </div>
            );
          })}

        </div>
      </section>

    </div>
  );
};
export default CaseStudies;
